/**
 * This file is part of CLaJ. The system that allows you to play with your friends,
 * just by creating a room, copying the link and sending it to your friends.
 * Copyright (c) 2025-2026  Xpdustry
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.xpdustry.claj.api;

import java.net.URI;
import java.net.URISyntaxException;

import com.xpdustry.claj.common.util.Strings;


/**
 * CLaJ links (for this version) are URI, and formatted like that: {@code claj://host:port/room-id}
 * or {@code host:port/room-id}.<br>
 * - {@code 'claj://'} is the protocol name (this part is optional). <br>
 * - {@code 'host'} is the host server. <br>
 * - {@code 'port'} is the server port to connect to. <br>
 * - {@code 'room-id'} is a base64 (url safe) encoded {@code long}, generated by the server and
 * given to the client that created the room.
 */
public class ClajLink {
  public static final String PROTOCOL = "claj";
  public static final String SCHEME = PROTOCOL + "://";

  public final URI uri;
  public final String host;
  public final int port;
  public final long roomId;
  public final String encodedRoomId;

  public ClajLink(String host, int port, String roomId) {
    if (host == null || host.isEmpty()) throw new IllegalArgumentException("Missing host");
    if (port == -1) throw new IllegalArgumentException("Missing port");
    if (roomId != null && roomId.indexOf('/') == 0) roomId = roomId.substring(1);
    if (roomId == null || roomId.isEmpty()) throw new IllegalArgumentException("Missing room id");

    this.host = host;
    this.port = port;
    try { this.roomId = Strings.base64ToLong(roomId); }
    catch (Exception e) { throw /*e;*/new IllegalArgumentException("Invalid room id"); }
    if (this.roomId == ClajProxy.UNCREATED_ROOM)
      throw new IllegalArgumentException("Invalid room id");
    this.encodedRoomId = roomId;

    try { uri = new URI(PROTOCOL, null, host, port, '/'+encodedRoomId, null, null); }
    // This error can only happen when the host is invalid
    catch (URISyntaxException _) { throw new IllegalArgumentException("Invalid host"); }
  }

  public ClajLink(String host, int port, long roomId) {
    if (host == null || host.isEmpty()) throw new IllegalArgumentException("Missing host");
    if (port == -1) throw new IllegalArgumentException("Missing port");

    this.host = host;
    this.port = port;
    this.roomId = roomId;
    if (this.roomId == ClajProxy.UNCREATED_ROOM)
      throw new IllegalArgumentException("Invalid room id");
    this.encodedRoomId = new String(Strings.longToBase64(roomId));

    try { uri = new URI(PROTOCOL, null, host, port, '/'+encodedRoomId, null, null); }
    // This error can only happen when the host is invalid
    catch (URISyntaxException _) { throw new IllegalArgumentException("Invalid host"); }
  }

  @Override
  public String toString() {
    return uri.toString();
  }

  @Override
  public boolean equals(Object o) {
    return this == o || o instanceof ClajLink link &&
           host.equals(link.host) && port == link.port && roomId == link.roomId;
  }

  @Override
  public int hashCode() {
    return (host.hashCode() * 31 + port) * 31 + Long.hashCode(roomId);
  }

  /** @throws IllegalArgumentException if the link is invalid */
  public static ClajLink fromString(String link) throws IllegalArgumentException {
    if (!link.contains("://") && !link.startsWith(SCHEME)) link = SCHEME+link;
    if (link.startsWith(PROTOCOL) &&
        (!link.startsWith(SCHEME) || link.length() == SCHEME.length()))
      throw new IllegalArgumentException("Missing host");

    URI uri;
    try { uri = URI.create(link); }
    catch (IllegalArgumentException e) {
      String cause = e.getLocalizedMessage();
      // Cut after semicolon as it's useless
      int semicolon = cause.indexOf(':');
      if (semicolon == -1) throw e;
      else throw new IllegalArgumentException(cause.substring(0, semicolon), e);
    }

    if (uri.isAbsolute() && !uri.getScheme().equals(PROTOCOL))
      throw new IllegalArgumentException("Not a CLaJ link");

    return new ClajLink(uri.getHost(), uri.getPort(), uri.getPath());
  }
}
